{{- if and .Values.benchmark.enabled .Values.benchmark.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "benchmark-charts.serviceAccountName" . }}
  namespace: {{ .Values.benchmark.namespace }}
  labels:
    {{- include "benchmark-charts.labels" . | nindent 4 }}
  {{- with .Values.benchmark.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
