s3ModelCopy:
  namespace: default
  model: NousResearch/Meta-Llama-3-8B-Instruct
  s3Bucket: my-models-bucket # S3 bucket name
  serviceAccountName: default # Ensure service account has S3 permissions
