model: moonshotai/Kimi-K3

extraLabels:
  ai.eks.amazonaws.com/name: kimi-k3-vllm

modelParameters:
  trustRemoteCode: true
  moeBackend: auto
  gpuMemoryUtilization: "0.95"
  tensorParallelSize: "8"
  maxModelLen: "1000000"
  kvCacheDtype: fp8
  attentionConfig: >-
    '{"mla_prefill_backend":"TRTLLM_RAGGED","use_prefill_query_quantization":true}'
  maxNumBatchedTokens: "32768"
  enablePrefixCaching: true
  enableAutoToolChoice: true
  toolCallParser: kimi_k3
  reasoningParser: kimi_k3
  enableMetrics: true
  enableMfuMetrics: true

inference:
  serviceName: kimi-k3-vllm
  serviceNamespace: default
  accelerator: gpu
  framework: vllm
  modelServer:
    image:
      repository: vllm/vllm-openai
      tag: kimi-k3
    env:
      VLLM_ENABLE_K3_LATENT_MOE_TAIL_FUSION: 1
      VLLM_ALLREDUCE_USE_FLASHINFER: 1
      VLLM_ENGINE_READY_TIMEOUT_S: 3600
      VLLM_USE_V2_MODEL_RUNNER: 1
      VLLM_USE_RUST_FRONTEND: 0
    deployment:
      instanceType: p6-b300.48xlarge
      sharedMemory: 50Gi
      resources:
        gpu:
          requests:
            nvidia.com/gpu: 8
          limits:
            nvidia.com/gpu: 8
      startupProbe:
        failureThreshold: 600
        periodSeconds: 10
        httpGet:
          path: /health
          port: 8000
